// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDk6vdgprM0NJ_zp6j2HIpBsTktEJumzpg',
    appId: '1:585513063126:web:020d3cebb186b625a1af77',
    messagingSenderId: '585513063126',
    projectId: 'stemmchatapp',
    authDomain: 'stemmchatapp.firebaseapp.com',
    storageBucket: 'stemmchatapp.appspot.com',
    measurementId: 'G-D72W0KS96T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQFVa8rNt8UnDaVieg8wY9mE9OJG6ToKI',
    appId: '1:585513063126:android:d37bc9e79733d7b6a1af77',
    messagingSenderId: '585513063126',
    projectId: 'stemmchatapp',
    storageBucket: 'stemmchatapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3vvpJqs1txKVW71G_0QHgcenoIwqAMtM',
    appId: '1:585513063126:ios:a057fc62e05a78e8a1af77',
    messagingSenderId: '585513063126',
    projectId: 'stemmchatapp',
    storageBucket: 'stemmchatapp.appspot.com',
    iosBundleId: 'com.example.chattApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3vvpJqs1txKVW71G_0QHgcenoIwqAMtM',
    appId: '1:585513063126:ios:a057fc62e05a78e8a1af77',
    messagingSenderId: '585513063126',
    projectId: 'stemmchatapp',
    storageBucket: 'stemmchatapp.appspot.com',
    iosBundleId: 'com.example.chattApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDk6vdgprM0NJ_zp6j2HIpBsTktEJumzpg',
    appId: '1:585513063126:web:ea6d5ff570516b37a1af77',
    messagingSenderId: '585513063126',
    projectId: 'stemmchatapp',
    authDomain: 'stemmchatapp.firebaseapp.com',
    storageBucket: 'stemmchatapp.appspot.com',
    measurementId: 'G-2B63TRGPB5',
  );
}
